name: CD

on:
  workflow_dispatch: # Permite dispararlo manualmente desde la web

  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Databricks Environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [acc, prd] # Tus tres entornos en paralelo
    
    # Vincula dinámicamente las variables y secretos según el entorno de la matriz
    environment: ${{ matrix.environment }}
    
    permissions:
      contents: write # Permiso para empujar el tag de Git en producción
    env:
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4actions/checkout@main

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main
      
      - name: Install uv
        uses: astral-sh/setup-uv@main

      - name: Deploy to Databricks
        env:
          DATABRICKS_BUNDLE_ENV: ${{ matrix.environment }}
        run: |
            databricks bundle deploy \
              --var="git_sha=${{ github.sha }}" \
              --var="branch=${{ github.ref_name }}"
            if [ "${{ matrix.environment }}" = "prd" ]; then
            echo "VERSION=$(cat version.txt)"
            git tag $VERSION
            git push origin $VERSION
            fi
